### ISSUE TITLE
Exception list not working fully.

### ISSUE THREAD

**Issue by Yaooay** [1NutWunDeR/KZTimer#11]
i tried to add the weapon paints plugin to my server and i added all 3 commands to the exceptions list. but every time the command is typed it comes up and then immediately disappears. its weird because all the other exceptions work just fine...

**Comment by AzaZPPL** [comment]
Weapon Paints uses a different way of opening menu's. So it wont work

**Comment by Yaooay** [comment]
i cant use this somehow?

https://forums.alliedmods.net/showpost.php?p=2265536&postcount=487

**Comment by AzaZPPL** [comment]
You could try adding that to your franug_weaponpaints.sp and running it.

**Comment by Yaooay** [comment]
where do i add it? iv been trying but it keeps saying "undefined symbol"

**Comment by Yaooay** [comment]
http://imgur.com/Y1Ly0aL

**Comment by Yaooay** [comment]
nevermind. the buy ammo thing worked. thanks aza
